title: Kodai Utsunomiya | 宇都宮 幸大
email: utsunomiya@mdl.cs.tsukuba.ac.jp
description: >-
  The personal website of Kodai Utsunomiya
baseurl: ""
url: "https://kodai-utsunomiya-mdl-github-io.vercel.app"
twitter_username: utsunomiya__k
github_username: kodai-utsunomiya-mdl

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
